Remove 99% of deprecated ioutil usage
linuxkit/linuxkit pull request #3842
Opened 2022-10-08 20:28 UTC by dgageot

Signed-off-by: David Gageot <david.gageot@docker.com>

2022-10-08 21:22 UTC, thaJeztah requested changes
Found some files where you forgot to add the `"io"` to imports, and left a comment on formatting the comments (mostly a nit as these functions are not exported)

2022-10-08 21:22 UTC, thaJeztah commented on pkg/metadata/provider_gcp.go
> +//
I think Go gets confused by these, and formats them as a `code` block, so instead, remove the indent, and add a colon (`:`) after `TODO`, that way GoDoc also picks them up correctly; see https://pkg.go.dev/github.com/fluhus/godoc-tricks#Bugs;

```suggestion
// TODO: also retrieve the instance keys and respect block
// project keys see:
// https://cloud.google.com/compute/docs/instances/ssh-keys
//
```

2022-10-08 21:22 UTC, thaJeztah commented on pkg/metadata/provider_gcp.go
> +	body, err := io.ReadAll(resp.Body)
You missed adding `"io"` as import in this file

2022-10-08 21:22 UTC, thaJeztah commented on pkg/metadata/provider_vultr.go
> -	"io/ioutil"
need to add `"io"` to imports here

2022-10-08 21:22 UTC, thaJeztah commented on pkg/metadata/provider_digitalocean.go
> -	"io/ioutil"
Need to add `"io"` to imports in this file

2022-10-08 21:22 UTC, thaJeztah commented on pkg/metadata/provider_hetzner.go
> -	"io/ioutil"
Same here

2022-10-08 21:22 UTC, thaJeztah commented on pkg/metadata/provider_metaldata.go
> -	"io/ioutil"
Here as well

2022-10-08 21:22 UTC, thaJeztah commented on pkg/metadata/provider_openstack.go
> -	"io/ioutil"
And here

2022-10-08 21:22 UTC, thaJeztah commented on pkg/metadata/provider_scaleway.go
> -	"io/ioutil"
Ditto

2022-10-09 07:11 UTC, dgageot commented
Sorry for the mess...

2022-10-09 07:33 UTC, deitch commented
Again, I would prefer if we split out the changes to the CLI `src/cmd/linuxkit` and the ones to packages `pkg/`. Just better risk management and ability to roll back if we have issues.

2022-10-09 08:38 UTC, deitch approved these changes

2022-10-09 12:53 UTC, merged